[Enhancement] Message/button should be more in line with design mockup when employee must have a "qualifying event"
associatedemployers/quartz pull request #130
Opened 2020-09-18 16:23 UTC by JavaLavaMT

closes #119

<img width="710" alt="Screen Shot 2020-09-18 at 9 39 41 AM" src="https://user-images.githubusercontent.com/25805625/93621458-d01b0b80-f998-11ea-8561-ef83d0d5441f.png">
<img width="947" alt="Screen Shot 2020-09-18 at 9 39 50 AM" src="https://user-images.githubusercontent.com/25805625/93621463-d1e4cf00-f998-11ea-8f18-1f0b44eaf141.png">

2020-09-21 12:17 UTC, James1x0 requested changes

2020-09-21 12:17 UTC, James1x0 commented on app/controllers/account/benefits/index.js
> +  ];
Move this to statics in config

2020-09-21 12:17 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +            In order to make changes, you mush have a qualifying event.
```suggestion
            In order to make changes, you must have a qualifying event.
```
![](https://lh3.googleusercontent.com/proxy/5K0KOd83QBFK83vPV9_Syco89zH7xs0XqoTSqaJ7PEn8BBirTeKQEI_GiI9RQzHDSuNcA5XewRygSxyAA6Q-Tdwjqcq8GrjPWLheAjjfhZfCObSXgq1Q_Sd_ci6pdVAixyjaFqeXlXAWUAjJYTLuZaNFoyGtMgwPQwDAONcIew)

2020-09-21 12:17 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +              <EmberPopover @side="right" @popperContainer="body">
```suggestion
              <EmberTooltip @side="right" @popperContainer="body">
```

2020-09-21 12:17 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +              </EmberPopover>
```suggestion
              </EmberTooltip>
```

2020-09-21 12:17 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +                {{/each}}
```suggestion
                <ul>
                  {{#each this.qualifyingEvents as |event|}}
                    <li>{{event}}</li>
                  {{/each}}
                </ul>
```

2020-09-22 19:29 UTC, JavaLavaMT commented on app/templates/account/benefits/index.hbs
> +              <EmberPopover @side="right" @popperContainer="body">
when using tooltip the info seems to wrap

![image](https://user-images.githubusercontent.com/25805625/93927998-e0075800-fcd6-11ea-932f-62ee419092b3.png)

2020-09-22 19:29 UTC, JavaLavaMT commented on app/templates/account/benefits/index.hbs
> +                {{/each}}
I had it with the list, but as you said  😃 
![image](https://user-images.githubusercontent.com/25805625/93928279-4c825700-fcd7-11ea-8df0-16a724ea18b7.png)

![image](https://user-images.githubusercontent.com/25805625/93928214-2f4d8880-fcd7-11ea-9165-29e818899cd2.png)

2020-09-22 19:32 UTC, JavaLavaMT commented on app/controllers/account/benefits/index.js
> +  ];
🏁

2020-09-22 19:37 UTC, JavaLavaMT commented on app/templates/account/benefits/index.hbs
> +            In order to make changes, you mush have a qualifying event.
🏁

2020-09-24 13:51 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +                {{/each}}
The difference is, this looks a lot better than the errors that were being displayed in that message.

2020-09-24 13:51 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +                {{/each}}
Solidify the list! 😄

2020-09-24 13:52 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +              <EmberPopover @side="right" @popperContainer="body">
Less of a problem with the list 😏

2020-09-24 13:54 UTC, James1x0 requested changes
Still needs a list for qual events

2020-10-06 16:29 UTC, merged