[Feautre] Beneficiary designation
associatedemployers/quartz pull request #132
Opened 2020-09-22 19:01 UTC by JavaLavaMT

closes #123 

![image](https://user-images.githubusercontent.com/25805625/93923873-34a7d480-fcd1-11ea-8ccf-a3c3d613287a.png)

![image](https://user-images.githubusercontent.com/25805625/93923899-3c677900-fcd1-11ea-8661-5787872a643d.png)

2020-09-24 15:00 UTC, James1x0 requested changes

2020-09-24 15:00 UTC, James1x0 commented on app/controllers/account/benefits/enrollment/beneficiaries.js
> +  }
This is going to duplicate beneficiaries

2020-10-05 20:28 UTC, JavaLavaMT commented on app/config/statics.js
> +];
🏁

2020-10-05 20:29 UTC, JavaLavaMT commented on app/models/beneficiary.js
> +});
🏁

2020-10-05 20:29 UTC, JavaLavaMT commented on app/controllers/account/benefits/enrollment/beneficiaries.js
> +  }
I was way over thinking this

2020-10-05 20:29 UTC, JavaLavaMT commented on app/controllers/account/benefits/enrollment/beneficiaries.js
> +  }
🏁

2020-10-06 16:28 UTC, merged