[Feature] Review Page
associatedemployers/quartz pull request #145
Opened 2020-10-08 20:44 UTC by JavaLavaMT

closes #126
close with associatedemployers/igneous#360

did issue, fixed beneficiary id, and fixed the next button on elections

![image](https://user-images.githubusercontent.com/25805625/95511337-8fe5f200-0974-11eb-99f8-bcf062655db8.png)

![image](https://user-images.githubusercontent.com/25805625/95511377-9c6a4a80-0974-11eb-88a7-2bde8420eb94.png)

![image](https://user-images.githubusercontent.com/25805625/95511307-85c3f380-0974-11eb-85b4-953f8c19b5ee.png)

2020-10-09 13:29 UTC, James1x0 requested changes

2020-10-09 13:29 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +              {{this.spouse.fistName}} {{this.spouse.lastName}} -
fistname 👊

2020-10-09 13:29 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +            {{#if this.spouse}}
Meh, spouse in some cases could actually be a domestic partner. Please use the value from the relationship field, instead of this. Adjust your model to indicate a "significant other". See https://github.com/associatedemployers/quartz/blob/feature/enrollment/app/components/enrollment/coverage-level-selection.js#L37-L50

2020-10-09 13:29 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +          {{/if}}
Indentation here is confusing, and makes it look like we are missing an {{/if}}

2020-10-09 13:29 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +      <div class="ui raised minimally padded segment container">
```suggestion
      <div class="ui raised padded segment container">
```

2020-10-09 13:29 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +<div class="signature ui equal width grid">
Not understanding why this is a grid... If you need padding use a basic segment that's padded.

2020-10-09 13:29 UTC, James1x0 commented on app/models/enrollment.js
> +  @attr('boolean') reviewedEnrollment
If we are going to have a flag for this (not opposed), it needs to be a `date`

2020-10-09 13:29 UTC, James1x0 commented on app/models/enrollment.js
> +  @attr('string') signature
In addition to the signature, we'll need to capture the IP for the signature via a conditional `alterPayload`. See 
Config method: https://github.com/associatedemployers/igneous/blob/fff3f0490fe2bfe0327a21e441bffe3ab699331f/api/file-assignments/config.js#L13-L20
Middleware:
https://github.com/associatedemployers/igneous/blob/03d2bb729c849c2a0cf985ef5f0bcec69b417c16/lib/models/file-assignment/middleware/effects/fill-file.js#L21-L24

signedOn, and signatureIP should **not** be directly writable by a client.

If you have questions, don't guess, lmk.

2020-10-09 13:29 UTC, James1x0 commented on app/models/beneficiary.js
> +  @attr('number') enrollmentId;
```suggestion
```

2020-10-09 13:30 UTC, James1x0 commented on app/templates/account/benefits/enrollment/review.hbs
> +        @company={{this.model.employee.company}} />
One more thing, add a property to disable the "show/hide" mechanism and disable it here.

2020-10-09 15:05 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +              {{this.spouse.fistName}} {{this.spouse.lastName}} -
🏁  😆

2020-10-12 17:59 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +        @company={{this.model.employee.company}} />
🏁

2020-10-12 17:59 UTC, JavaLavaMT commented on app/models/beneficiary.js
> +  @attr('number') enrollmentId;
🏁

2020-10-12 17:59 UTC, JavaLavaMT commented on app/models/enrollment.js
> +  @attr('boolean') reviewedEnrollment
🏁

2020-10-12 18:00 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +<div class="signature ui equal width grid">
was in the habit of grids haha 🏁

2020-10-12 18:00 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +      <div class="ui raised minimally padded segment container">
🏁

2020-10-12 18:10 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +          {{/if}}
🏁

2020-10-12 18:10 UTC, JavaLavaMT commented on app/templates/account/benefits/enrollment/review.hbs
> +            {{#if this.spouse}}
🏁

2020-10-15 13:43 UTC, James1x0 requested changes

2020-10-15 13:43 UTC, James1x0 commented on app/routes/account/benefits/enrollment/beneficiaries.js
> +        enrollmentId: model.enrollment.id,
```suggestion
```

2020-10-15 13:43 UTC, James1x0 commented on app/routes/account/benefits/enrollment/beneficiaries.js
> +        enrollmentId: model.enrollment.id,
```suggestion
```

2020-10-15 13:43 UTC, James1x0 commented on app/templates/account/benefits/enrollment/elect.hbs
> +</form>
```suggestion
<form class="ui form" {{on "submit" (prevent-default (route-action "saveAndContinue"))}}>
  <div class="ui divider"></div>
  <Form::ActionButton type="submit" class="ui huge fluid green button" @loading={{this.data.statuses.wizard.isLoading}}>
    Next: Beneficiaries
  </Form::ActionButton>
</form>
```

2020-10-15 13:44 UTC, merged