[Feature] Qualifying event page
associatedemployers/quartz pull request #165
Opened 2020-10-21 15:57 UTC by JavaLavaMT

closes #147
closed with associatedemployers/igneous#369
removed param for enrollment as it is not needed

![image](https://user-images.githubusercontent.com/25805625/96745477-6751f500-1383-11eb-974f-7af53bed31b1.png)
![image](https://user-images.githubusercontent.com/25805625/96745511-7173f380-1383-11eb-96b4-82dbccca95bd.png)
![image](https://user-images.githubusercontent.com/25805625/96745540-79cc2e80-1383-11eb-9872-776eb53a6ba3.png)
![image](https://user-images.githubusercontent.com/25805625/96745575-83559680-1383-11eb-9e8a-3c1e8ded3ca6.png)
![image](https://user-images.githubusercontent.com/25805625/96745611-8fd9ef00-1383-11eb-9037-dd905595494d.png)

2020-10-26 19:42 UTC, James1x0 requested changes

2020-10-26 19:42 UTC, James1x0 commented on app/routes/account/benefits/index.js
> +      enrollment:     eligibility.enrollment._id && this.store.peekRecord('enrollment', eligibility.enrollment._id)
This would start edits for a non-pending record if one was recorded. That's no dice.

2020-10-26 19:42 UTC, James1x0 commented on app/templates/account/benefits/index.hbs
> +        <a href="#" role="button" class="ui button__segment-attached--bottom blue large button" {{on "click" (prevent-default this.openModal)}}>
It looks like a button... it's labelled like a button... it's a button.

```suggestion
        <button type="button" class="ui button__segment-attached--bottom blue large button" {{on "click" (prevent-default this.openModal)}}>
```

2020-10-26 19:42 UTC, James1x0 commented on app/controllers/account/benefits/index.js
> +    description:    'Qualifying ife event',
```suggestion
    description:    'Qualifying life event',
```

2020-10-26 19:42 UTC, James1x0 commented on app/controllers/account/benefits/index.js
> +    return this.model.enrollment.qualifyingEvent && (this.qualifyingEvents[this.model.enrollment.qualifyingEvent] || []).document ?  this.qualifyingEvents[this.model.enrollment.qualifyingEvent].docum
This is here, but weirdly seems like you're not utilizing it. This should display proper document names.

2020-10-29 20:43 UTC, JavaLavaMT commented on app/controllers/account/benefits/index.js
> +    return this.model.enrollment.qualifyingEvent && (this.qualifyingEvents[this.model.enrollment.qualifyingEvent] || []).document ?  this.qualifyingEvents[this.model.enrollment.qualifyingEvent].docum
🏁

2020-11-02 16:25 UTC, JavaLavaMT commented on app/controllers/account/benefits/index.js
> +    return this.model.enrollment.qualifyingEvent && (this.qualifyingEvents[this.model.enrollment.qualifyingEvent] || []).document ?  this.qualifyingEvents[this.model.enrollment.qualifyingEvent].docum
![image](https://user-images.githubusercontent.com/25805625/97892442-3b246580-1ced-11eb-8030-94e9070d250d.png)

![image](https://user-images.githubusercontent.com/25805625/97892496-4d060880-1ced-11eb-94ea-1ea3362e5b7c.png)

![image](https://user-images.githubusercontent.com/25805625/97892517-555e4380-1ced-11eb-815b-260a544700e0.png)

2020-11-02 16:25 UTC, JavaLavaMT commented on app/controllers/account/benefits/index.js
> +    description:    'Qualifying ife event',
🏁

2020-11-02 16:25 UTC, JavaLavaMT commented on app/templates/account/benefits/index.hbs
> +        <a href="#" role="button" class="ui button__segment-attached--bottom blue large button" {{on "click" (prevent-default this.openModal)}}>
🏁

2020-11-02 16:25 UTC, JavaLavaMT commented on app/routes/account/benefits/index.js
> +      enrollment:     eligibility.enrollment._id && this.store.peekRecord('enrollment', eligibility.enrollment._id)
🏁

2020-11-16 17:18 UTC, merged